# Generated by Django 5.0.7 on 2024-07-20 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0002_assessmenttype'),
        ('dept_faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
        migrations.CreateModel(
            name='AddAssessmentScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.assessmenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_faculty.students')),
            ],
            options={
                'db_table': 'add_assessment_score',
            },
        ),
    ]
