# Generated by Django 5.0.7 on 2024-08-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0008_alter_facultyadmin_dpt_admin'),
        ('dept_faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='clg_admin.batch'),
        ),
    ]
