# Generated by Django 5.0.7 on 2024-08-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='department',
        ),
    ]
