# Generated by Django 5.0.7 on 2024-07-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0002_assessmenttype'),
        ('dept_faculty', '0002_alter_students_table_addassessmentscore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addassessmentscore',
            unique_together={('student', 'assessment')},
        ),
    ]
