# Generated by Django 5.0.7 on 2024-08-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0009_alter_facultyadmin_department_and_more'),
        ('dept_faculty', '0005_alter_addassessmentscore_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addassessmentscore',
            unique_together={('student', 'assessment')},
        ),
    ]
