# Generated by Django 5.0.7 on 2024-08-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0012_alter_facultyroles_name'),
        ('dept_admin', '0005_alter_facultyallocation_options'),
        ('dept_faculty', '0007_alter_addassessmentscore_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addassessmentscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='addassessmentscore',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clg_admin.semester'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='addassessmentscore',
            unique_together={('student', 'assessment', 'subject', 'semester')},
        ),
    ]
