# Generated by Django 5.0.7 on 2024-08-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_faculty', '0009_alter_addassessmentscore_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'db_table': 'scorestatus',
            },
        ),
        migrations.AddField(
            model_name='addassessmentscore',
            name='status',
            field=models.ManyToManyField(to='dept_faculty.scorestatus'),
        ),
    ]
