# Generated by Django 5.0.7 on 2024-08-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_faculty', '0013_alter_students_reg_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addassessmentscore',
            options={'verbose_name': 'Generate MarkList'},
        ),
        migrations.AddField(
            model_name='addassessmentscore',
            name='month',
            field=models.CharField(default='September - 2024', max_length=50),
        ),
    ]
