# Generated by Django 5.0.7 on 2024-07-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clg_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.department')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_admin.courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.subjects')),
            ],
            options={
                'db_table': 'subject_allocation',
            },
        ),
    ]
