# Generated by Django 5.0.7 on 2024-08-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0008_alter_facultyadmin_dpt_admin'),
        ('dept_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectallocation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.faculty'),
        ),
    ]
