# Generated by Django 5.0.7 on 2024-07-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0001_initial'),
        ('dept_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.faculty')),
            ],
            options={
                'db_table': 'faculty_allocation',
            },
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_admin.facultyallocation'),
        ),
    ]
