# Generated by Django 5.0.7 on 2024-08-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0008_alter_facultyadmin_dpt_admin'),
        ('dept_admin', '0002_alter_subjectallocation_faculty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together={('subject', 'course', 'batch')},
        ),
        migrations.RemoveField(
            model_name='subjectallocation',
            name='department',
        ),
    ]
