# Generated by Django 5.0.7 on 2024-08-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0009_alter_facultyadmin_department_and_more'),
        ('dept_admin', '0003_alter_subjectallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together={('subject', 'course', 'batch', 'faculty')},
        ),
    ]
