# Generated by Django 5.0.7 on 2024-08-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_admin', '0004_alter_subjectallocation_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyallocation',
            options={'verbose_name': 'Class Tutors'},
        ),
    ]
