# Generated by Django 5.0.7 on 2024-08-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_admin', '0006_alter_subjectallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='facultyallocation',
            options={'verbose_name': 'Class Tutor'},
        ),
        migrations.AlterModelOptions(
            name='subjectallocation',
            options={'verbose_name': 'Subject Allocation'},
        ),
    ]
