# Generated by Django 5.0.7 on 2024-08-21 07:35

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_control', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='eg. 2024-08-21', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1904, 9, 20)), django.core.validators.MaxValueValidator(datetime.date(2006, 8, 26))]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
