# Generated by Django 5.0.7 on 2024-07-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_control', '0003_remove_customuser_is_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
