# Generated by Django 5.0.7 on 2024-08-22 15:00

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_control', '0003_alter_customuser_dob_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='eg. 2024-08-22', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1904, 9, 21)), django.core.validators.MaxValueValidator(datetime.date(2006, 8, 27))]),
        ),
    ]
