# Generated by Django 5.0.7 on 2024-08-19 16:50

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_control', '0005_alter_customuser_options_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Manage Profile', 'verbose_name_plural': 'Manage Profiles'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/faculty/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='eg. 2024-08-19', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1904, 9, 18)), django.core.validators.MaxValueValidator(datetime.date(2006, 8, 24))]),
        ),
    ]
