# Generated by Django 5.0.7 on 2024-08-29 03:22

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_control', '0006_alter_customuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='eg. 2024-08-29', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1904, 9, 28)), django.core.validators.MaxValueValidator(datetime.date(2006, 9, 3))]),
        ),
    ]
