# Generated by Django 5.0.7 on 2024-07-20 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_from_date', models.IntegerField()),
                ('batch_to_date', models.IntegerField()),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'regulation',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joining_date', models.DateField()),
                ('major_study', models.CharField(blank=True, max_length=200, null=True)),
                ('faculty_type', models.CharField(choices=[('Department Admin', 'Department Admin'), ('Department Staff', 'Department Staff')], default='Department Staff', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/faculty/%Y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='FacultyAdmin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_appointed', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.department')),
                ('dpt_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.faculty')),
            ],
            options={
                'db_table': 'faculty_admin',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.regulation')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
    ]
