# Generated by Django 5.0.7 on 2024-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0002_assessmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='name',
            field=models.CharField(default='Null', max_length=200),
            preserve_default=False,
        ),
    ]
