# Generated by Django 5.0.7 on 2024-08-14 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0004_alter_department_name_alter_facultyadmin_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyadmin',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.department'),
        ),
        migrations.AlterField(
            model_name='facultyadmin',
            name='dpt_admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.faculty'),
        ),
    ]
