# Generated by Django 5.0.7 on 2024-08-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0005_alter_facultyadmin_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='photo',
        ),
    ]
