# Generated by Django 5.0.7 on 2024-08-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0007_alter_faculty_faculty_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyadmin',
            name='dpt_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.faculty'),
        ),
    ]
