# Generated by Django 5.0.7 on 2024-08-22 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0008_alter_facultyadmin_dpt_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyadmin',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.department', unique=True),
        ),
        migrations.AlterField(
            model_name='facultyadmin',
            name='dpt_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.faculty', unique=True),
        ),
    ]
