# Generated by Django 5.0.7 on 2024-08-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0009_alter_facultyadmin_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRoles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Department HOD', 'Department HOD'), ('Department Staff', 'Department Staff'), ('Class Tutor', 'Class Tutor')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'faculty_roles',
            },
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_type',
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_type',
            field=models.ManyToManyField(to='clg_admin.facultyroles'),
        ),
    ]
