# Generated by Django 5.0.7 on 2024-08-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0010_facultyroles_remove_faculty_faculty_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyroles',
            name='name',
            field=models.CharField(choices=[('Department HOD', 'Department HOD'), ('Department Staff', 'Department Staff'), ('Class Tutor', 'Class Tutor')], default='Department Staff', max_length=50, unique=True),
        ),
    ]
