# Generated by Django 5.0.7 on 2024-08-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0011_alter_facultyroles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyroles',
            name='name',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('FacultyAdmin', 'FacultyAdmin'), ('Class Tutor', 'Class Tutor')], default='Department Staff', max_length=50, unique=True),
        ),
    ]
