# Generated by Django 5.0.7 on 2024-08-30 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_admin', '0012_alter_facultyroles_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveLetter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg_admin.faculty')),
            ],
            options={
                'db_table': 'leave_letter',
            },
        ),
    ]
